"""
Settings page for Visual RAG Document Explorer.

Provides comprehensive configuration management for all system components.
"""

import streamlit as st
from pathlib import Path
import json
from typing import Dict, Any, Optional
import os

from config.settings import Settings
from ui.components import render_sidebar


def initialize_session_state() -> None:
    """Initialize session state variables for settings page."""
    if "settings_modified" not in st.session_state:
        st.session_state.settings_modified = False
    if "settings_data" not in st.session_state:
        # Load current settings
        settings = Settings()
        st.session_state.settings_data = settings.model_dump()


def save_settings_to_file(settings_data: Dict[str, Any], filepath: str) -> bool:
    """
    Save settings to a JSON file.
    
    Args:
        settings_data: Settings dictionary
        filepath: Path to save file
        
    Returns:
        True if successful, False otherwise
    """
    try:
        with open(filepath, 'w') as f:
            json.dump(settings_data, f, indent=2)
        return True
    except Exception as e:
        st.error(f"Error saving settings: {str(e)}")
        return False


def load_settings_from_file(filepath: str) -> Optional[Dict[str, Any]]:
    """
    Load settings from a JSON file.
    
    Args:
        filepath: Path to settings file
        
    Returns:
        Settings dictionary or None if error
    """
    try:
        with open(filepath, 'r') as f:
            return json.load(f)
    except Exception as e:
        st.error(f"Error loading settings: {str(e)}")
        return None


def update_env_file(settings_data: Dict[str, Any]) -> bool:
    """
    Update .env file with new settings.
    
    Args:
        settings_data: Settings dictionary
        
    Returns:
        True if successful, False otherwise
    """
    try:
        env_path = Path(".env")
        
        # Read existing .env if it exists
        env_vars = {}
        if env_path.exists():
            with open(env_path, 'r') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        env_vars[key.strip()] = value.strip()
        
        # Update with new settings
        env_mapping = {
            "openai_api_key": "OPENAI_API_KEY",
            "openrouter_api_key": "OPENROUTER_API_KEY",
            "voyage_api_key": "VOYAGE_API_KEY",
            "cohere_api_key": "COHERE_API_KEY",
            "default_llm_provider": "DEFAULT_LLM_PROVIDER",
            "default_model": "DEFAULT_MODEL",
            "openrouter_model": "OPENROUTER_MODEL",
            "temperature": "TEMPERATURE",
            "max_tokens": "MAX_TOKENS",
            "default_embedding_model": "DEFAULT_EMBEDDING_MODEL",
            "voyage_model": "VOYAGE_MODEL",
            "bge_model": "BGE_MODEL",
            "default_vector_db": "DEFAULT_VECTOR_DB",
            "qdrant_url": "QDRANT_URL",
            "qdrant_collection": "QDRANT_COLLECTION",
            "milvus_url": "MILVUS_URL",
            "milvus_collection": "MILVUS_COLLECTION",
            "chunk_size_min": "CHUNK_SIZE_MIN",
            "chunk_size_max": "CHUNK_SIZE_MAX",
            "chunk_overlap": "CHUNK_OVERLAP",
            "ner_mode": "NER_MODE",
            "gliner_model": "GLINER_MODEL",
            "spacy_model": "SPACY_MODEL",
            "search_mode": "SEARCH_MODE",
            "default_rag_strategy": "DEFAULT_RAG_STRATEGY",
            "enable_hyde": "ENABLE_HYDE",
            "enable_compression": "ENABLE_COMPRESSION",
            "srag_max_iterations": "SRAG_MAX_ITERATIONS",
            "srag_quality_threshold": "SRAG_QUALITY_THRESHOLD",
            "crag_relevance_threshold": "CRAG_RELEVANCE_THRESHOLD",
            "short_term_memory_size": "SHORT_TERM_MEMORY_SIZE",
            "enable_long_term_memory": "ENABLE_LONG_TERM_MEMORY",
        }
        
        for key, env_key in env_mapping.items():
            if key in settings_data:
                value = settings_data[key]
                # Convert boolean to string
                if isinstance(value, bool):
                    value = str(value).lower()
                env_vars[env_key] = str(value)
        
        # Write back to .env
        with open(env_path, 'w') as f:
            f.write("# Visual RAG Document Explorer Configuration\n")
            f.write("# Generated by Settings UI\n\n")
            
            # Group by category
            f.write("# ============= API Keys =============\n")
            for key in ["OPENAI_API_KEY", "OPENROUTER_API_KEY", "VOYAGE_API_KEY", "COHERE_API_KEY"]:
                if key in env_vars:
                    f.write(f"{key}={env_vars[key]}\n")
            
            f.write("\n# ============= LLM Settings =============\n")
            for key in ["DEFAULT_LLM_PROVIDER", "DEFAULT_MODEL", "OPENROUTER_MODEL", "TEMPERATURE", "MAX_TOKENS"]:
                if key in env_vars:
                    f.write(f"{key}={env_vars[key]}\n")
            
            f.write("\n# ============= Embedding Settings =============\n")
            for key in ["DEFAULT_EMBEDDING_MODEL", "VOYAGE_MODEL", "BGE_MODEL"]:
                if key in env_vars:
                    f.write(f"{key}={env_vars[key]}\n")
            
            f.write("\n# ============= Vector DB Settings =============\n")
            for key in ["DEFAULT_VECTOR_DB", "QDRANT_URL", "QDRANT_COLLECTION", "MILVUS_URL", "MILVUS_COLLECTION"]:
                if key in env_vars:
                    f.write(f"{key}={env_vars[key]}\n")
            
            f.write("\n# ============= Other Settings =============\n")
            for key, value in env_vars.items():
                if key not in ["OPENAI_API_KEY", "OPENROUTER_API_KEY", "VOYAGE_API_KEY", "COHERE_API_KEY",
                              "DEFAULT_LLM_PROVIDER", "DEFAULT_MODEL", "OPENROUTER_MODEL", "TEMPERATURE", "MAX_TOKENS",
                              "DEFAULT_EMBEDDING_MODEL", "VOYAGE_MODEL", "BGE_MODEL",
                              "DEFAULT_VECTOR_DB", "QDRANT_URL", "QDRANT_COLLECTION", "MILVUS_URL", "MILVUS_COLLECTION"]:
                    f.write(f"{key}={value}\n")
        
        return True
    except Exception as e:
        st.error(f"Error updating .env file: {str(e)}")
        return False


def render_llm_settings() -> Dict[str, Any]:
    """
    Render LLM provider settings section.
    
    Returns:
        Dictionary of LLM settings
    """
    st.subheader("🤖 LLM Provider Settings")
    
    settings = {}
    
    col1, col2 = st.columns(2)
    
    with col1:
        settings["default_llm_provider"] = st.selectbox(
            "Provider",
            options=["openai", "openrouter"],
            index=0 if st.session_state.settings_data.get("default_llm_provider") == "openai" else 1,
            help="Select the LLM provider to use"
        )
    
    with col2:
        if settings["default_llm_provider"] == "openai":
            settings["default_model"] = st.selectbox(
                "Model",
                options=["gpt-4o", "gpt-4o-mini", "gpt-4-turbo", "gpt-3.5-turbo"],
                index=0,
                help="OpenAI model to use"
            )
        else:
            settings["openrouter_model"] = st.selectbox(
                "Model",
                options=[
                    "anthropic/claude-sonnet-4",
                    "anthropic/claude-3.5-sonnet",
                    "anthropic/claude-3-opus",
                    "google/gemini-pro-1.5",
                    "meta-llama/llama-3.1-70b-instruct"
                ],
                index=0,
                help="OpenRouter model to use"
            )
    
    # API Keys
    if settings["default_llm_provider"] == "openai":
        settings["openai_api_key"] = st.text_input(
            "OpenAI API Key",
            value=st.session_state.settings_data.get("openai_api_key", ""),
            type="password",
            help="Your OpenAI API key"
        )
    else:
        settings["openrouter_api_key"] = st.text_input(
            "OpenRouter API Key",
            value=st.session_state.settings_data.get("openrouter_api_key", ""),
            type="password",
            help="Your OpenRouter API key"
        )
    
    # Generation parameters
    col1, col2 = st.columns(2)
    
    with col1:
        settings["temperature"] = st.slider(
            "Temperature",
            min_value=0.0,
            max_value=2.0,
            value=float(st.session_state.settings_data.get("temperature", 0.0)),
            step=0.1,
            help="Controls randomness in generation (0 = deterministic, 2 = very random)"
        )
    
    with col2:
        settings["max_tokens"] = st.slider(
            "Max Tokens",
            min_value=100,
            max_value=4000,
            value=int(st.session_state.settings_data.get("max_tokens", 2048)),
            step=100,
            help="Maximum number of tokens to generate"
        )
    
    return settings


def render_embedding_settings() -> Dict[str, Any]:
    """
    Render embedding model settings section.
    
    Returns:
        Dictionary of embedding settings
    """
    st.subheader("🔢 Embedding Settings")
    
    settings = {}
    
    col1, col2 = st.columns(2)
    
    with col1:
        settings["default_embedding_model"] = st.selectbox(
            "Embedding Model",
            options=["voyage", "bge-m3"],
            index=0 if st.session_state.settings_data.get("default_embedding_model") == "voyage" else 1,
            help="Select the embedding model to use"
        )
    
    with col2:
        if settings["default_embedding_model"] == "voyage":
            settings["voyage_model"] = st.selectbox(
                "Voyage Model",
                options=["voyage-3", "voyage-2", "voyage-large-2"],
                index=0,
                help="Voyage AI model variant"
            )
    
    # API Key for Voyage
    if settings["default_embedding_model"] == "voyage":
        settings["voyage_api_key"] = st.text_input(
            "Voyage API Key",
            value=st.session_state.settings_data.get("voyage_api_key", ""),
            type="password",
            help="Your Voyage AI API key"
        )
    
    return settings


def render_vectordb_settings() -> Dict[str, Any]:
    """
    Render vector database settings section.
    
    Returns:
        Dictionary of vector DB settings
    """
    st.subheader("🗄️ Vector Database Settings")
    
    settings = {}
    
    settings["default_vector_db"] = st.selectbox(
        "Database",
        options=["qdrant", "milvus"],
        index=0 if st.session_state.settings_data.get("default_vector_db") == "qdrant" else 1,
        help="Select the vector database to use"
    )
    
    if settings["default_vector_db"] == "qdrant":
        col1, col2 = st.columns(2)
        
        with col1:
            settings["qdrant_url"] = st.text_input(
                "Qdrant URL",
                value=st.session_state.settings_data.get("qdrant_url", "http://localhost:6333"),
                help="Qdrant server URL"
            )
        
        with col2:
            settings["qdrant_collection"] = st.text_input(
                "Collection Name",
                value=st.session_state.settings_data.get("qdrant_collection", "documents"),
                help="Qdrant collection name"
            )
    else:
        col1, col2 = st.columns(2)
        
        with col1:
            settings["milvus_url"] = st.text_input(
                "Milvus URL",
                value=st.session_state.settings_data.get("milvus_url", "http://localhost:19530"),
                help="Milvus server URL"
            )
        
        with col2:
            settings["milvus_collection"] = st.text_input(
                "Collection Name",
                value=st.session_state.settings_data.get("milvus_collection", "documents"),
                help="Milvus collection name"
            )
    
    return settings


def render_chunking_settings() -> Dict[str, Any]:
    """
    Render document chunking settings section.
    
    Returns:
        Dictionary of chunking settings
    """
    st.subheader("✂️ Chunking Settings")
    
    settings = {}
    
    col1, col2, col3 = st.columns(3)
    
    with col1:
        settings["chunk_size_min"] = st.number_input(
            "Min Chunk Size",
            min_value=128,
            max_value=2048,
            value=int(st.session_state.settings_data.get("chunk_size_min", 256)),
            step=64,
            help="Minimum chunk size in characters"
        )
    
    with col2:
        settings["chunk_size_max"] = st.number_input(
            "Max Chunk Size",
            min_value=256,
            max_value=4096,
            value=int(st.session_state.settings_data.get("chunk_size_max", 1024)),
            step=64,
            help="Maximum chunk size in characters"
        )
    
    with col3:
        settings["chunk_overlap"] = st.number_input(
            "Chunk Overlap",
            min_value=0,
            max_value=512,
            value=int(st.session_state.settings_data.get("chunk_overlap", 128)),
            step=32,
            help="Overlap between consecutive chunks"
        )
    
    return settings


def render_rag_settings() -> Dict[str, Any]:
    """
    Render RAG strategy settings section.
    
    Returns:
        Dictionary of RAG settings
    """
    st.subheader("🎯 RAG Settings")
    
    settings = {}
    
    col1, col2 = st.columns(2)
    
    with col1:
        settings["default_rag_strategy"] = st.selectbox(
            "Default Strategy",
            options=["auto", "simple", "crag", "srag", "advanced"],
            index=0,
            help="Default RAG strategy to use"
        )
    
    with col2:
        settings["search_mode"] = st.selectbox(
            "Search Mode",
            options=["hybrid", "dense", "sparse"],
            index=0,
            help="Search mode: dense (semantic), sparse (BM25), or hybrid (RRF fusion)"
        )
    
    # Boolean toggles
    col1, col2 = st.columns(2)
    
    with col1:
        settings["enable_hyde"] = st.checkbox(
            "Enable HyDE by Default",
            value=st.session_state.settings_data.get("enable_hyde", False),
            help="Use Hypothetical Document Embeddings for query expansion"
        )
    
    with col2:
        settings["enable_compression"] = st.checkbox(
            "Enable Compression by Default",
            value=st.session_state.settings_data.get("enable_compression", True),
            help="Use contextual compression to extract relevant portions"
        )
    
    # CRAG settings
    st.markdown("**CRAG Settings**")
    settings["crag_relevance_threshold"] = st.slider(
        "Relevance Threshold",
        min_value=0.0,
        max_value=1.0,
        value=float(st.session_state.settings_data.get("crag_relevance_threshold", 0.5)),
        step=0.05,
        help="Minimum relevance score for CRAG"
    )
    
    # SRAG settings
    st.markdown("**SRAG Settings**")
    col1, col2 = st.columns(2)
    
    with col1:
        settings["srag_max_iterations"] = st.number_input(
            "Max Iterations",
            min_value=1,
            max_value=10,
            value=int(st.session_state.settings_data.get("srag_max_iterations", 3)),
            help="Maximum self-reflection iterations"
        )
    
    with col2:
        settings["srag_quality_threshold"] = st.slider(
            "Quality Threshold",
            min_value=0.0,
            max_value=1.0,
            value=float(st.session_state.settings_data.get("srag_quality_threshold", 0.8)),
            step=0.05,
            help="Minimum quality score to stop iterations"
        )
    
    return settings


def render_ner_settings() -> Dict[str, Any]:
    """
    Render NER settings section.
    
    Returns:
        Dictionary of NER settings
    """
    st.subheader("🏷️ NER Settings")
    
    settings = {}
    
    settings["ner_mode"] = st.selectbox(
        "NER Mode",
        options=["ensemble", "gliner", "spacy"],
        index=0,
        help="Named Entity Recognition mode"
    )
    
    col1, col2 = st.columns(2)
    
    with col1:
        settings["gliner_model"] = st.text_input(
            "GLiNER Model",
            value=st.session_state.settings_data.get("gliner_model", "urchade/gliner_multi_pii-v1"),
            help="GLiNER model identifier"
        )
    
    with col2:
        settings["spacy_model"] = st.text_input(
            "spaCy Model",
            value=st.session_state.settings_data.get("spacy_model", "en_core_web_trf"),
            help="spaCy model identifier"
        )
    
    return settings


def render_memory_settings() -> Dict[str, Any]:
    """
    Render memory settings section.
    
    Returns:
        Dictionary of memory settings
    """
    st.subheader("🧠 Memory Settings")
    
    settings = {}
    
    col1, col2 = st.columns(2)
    
    with col1:
        settings["short_term_memory_size"] = st.number_input(
            "Short-term Memory Size",
            min_value=5,
            max_value=100,
            value=int(st.session_state.settings_data.get("short_term_memory_size", 20)),
            help="Number of recent messages to keep in memory"
        )
    
    with col2:
        settings["enable_long_term_memory"] = st.checkbox(
            "Enable Long-term Memory",
            value=st.session_state.settings_data.get("enable_long_term_memory", True),
            help="Store conversation history in vector database"
        )
    
    return settings


def main() -> None:
    """Main function for the Settings page."""
    st.set_page_config(
        page_title="Settings - Visual RAG",
        page_icon="⚙️",
        layout="wide"
    )
    
    # Initialize session state
    initialize_session_state()
    
    # Load settings
    settings = Settings()
    
    # Render sidebar
    system_status = {
        "vector_db_connected": True,
        "vector_db_type": settings.default_vector_db,
        "llm_provider": settings.default_llm_provider,
        "llm_model": settings.default_model
    }
    
    selected_page = render_sidebar(
        current_page="settings",
        system_status=system_status,
        stats=None
    )
    
    # Handle page navigation
    if selected_page != "settings":
        st.switch_page(f"ui/pages/{selected_page}.py")
    
    # Main content
    st.title("⚙️ Settings")
    st.markdown("Configure all aspects of the Visual RAG system")
    
    st.divider()
    
    # Collect all settings
    all_settings = {}
    
    # LLM Settings
    with st.expander("🤖 LLM Provider Settings", expanded=True):
        all_settings.update(render_llm_settings())
    
    # Embedding Settings
    with st.expander("🔢 Embedding Settings", expanded=False):
        all_settings.update(render_embedding_settings())
    
    # Vector DB Settings
    with st.expander("🗄️ Vector Database Settings", expanded=False):
        all_settings.update(render_vectordb_settings())
    
    # Chunking Settings
    with st.expander("✂️ Chunking Settings", expanded=False):
        all_settings.update(render_chunking_settings())
    
    # RAG Settings
    with st.expander("🎯 RAG Settings", expanded=False):
        all_settings.update(render_rag_settings())
    
    # NER Settings
    with st.expander("🏷️ NER Settings", expanded=False):
        all_settings.update(render_ner_settings())
    
    # Memory Settings
    with st.expander("🧠 Memory Settings", expanded=False):
        all_settings.update(render_memory_settings())
    
    st.divider()
    
    # Action buttons
    col1, col2, col3, col4 = st.columns(4)
    
    with col1:
        if st.button("💾 Apply Settings", type="primary", use_container_width=True):
            # Update session state
            st.session_state.settings_data.update(all_settings)
            
            # Update .env file
            if update_env_file(st.session_state.settings_data):
                st.success("✅ Settings applied successfully! Restart the application for changes to take effect.")
                st.session_state.settings_modified = False
            else:
                st.error("❌ Failed to apply settings")
    
    with col2:
        if st.button("📥 Save to File", use_container_width=True):
            # Save to JSON file
            save_path = st.text_input("Save path", value="settings_backup.json")
            if save_path:
                if save_settings_to_file(all_settings, save_path):
                    st.success(f"✅ Settings saved to {save_path}")
    
    with col3:
        if st.button("📤 Load from File", use_container_width=True):
            # Load from JSON file
            load_path = st.text_input("Load path", value="settings_backup.json")
            if load_path and Path(load_path).exists():
                loaded_settings = load_settings_from_file(load_path)
                if loaded_settings:
                    st.session_state.settings_data = loaded_settings
                    st.success(f"✅ Settings loaded from {load_path}")
                    st.rerun()
    
    with col4:
        if st.button("🔄 Reset to Defaults", use_container_width=True):
            # Reset to default settings
            default_settings = Settings()
            st.session_state.settings_data = default_settings.model_dump()
            st.success("✅ Settings reset to defaults")
            st.rerun()
    
    # Show current configuration summary
    st.divider()
    st.subheader("📋 Current Configuration Summary")
    
    summary_col1, summary_col2, summary_col3 = st.columns(3)
    
    with summary_col1:
        st.markdown("**LLM Configuration**")
        st.info(f"""
        Provider: {all_settings.get('default_llm_provider', 'N/A')}
        Model: {all_settings.get('default_model', all_settings.get('openrouter_model', 'N/A'))}
        Temperature: {all_settings.get('temperature', 'N/A')}
        """)
    
    with summary_col2:
        st.markdown("**Vector DB Configuration**")
        st.info(f"""
        Database: {all_settings.get('default_vector_db', 'N/A')}
        Embedding: {all_settings.get('default_embedding_model', 'N/A')}
        Search Mode: {all_settings.get('search_mode', 'N/A')}
        """)
    
    with summary_col3:
        st.markdown("**RAG Configuration**")
        st.info(f"""
        Strategy: {all_settings.get('default_rag_strategy', 'N/A')}
        HyDE: {'Enabled' if all_settings.get('enable_hyde', False) else 'Disabled'}
        Compression: {'Enabled' if all_settings.get('enable_compression', True) else 'Disabled'}
        """)


if __name__ == "__main__":
    main()
